// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJ7qFQHLcxtCPvYnO4umYtGvZTKWZReLU',
    appId: '1:151892709562:web:2c964f03a8ac90abf0b283',
    messagingSenderId: '151892709562',
    projectId: 'farm-erp-2023',
    authDomain: 'farm-erp-2023.firebaseapp.com',
    databaseURL: 'https://farm-erp-2023-default-rtdb.firebaseio.com',
    storageBucket: 'farm-erp-2023.appspot.com',
    measurementId: 'G-5BLR9M84L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmCpLWp5fXJR7EhuNDP7vuV66JA2GxMHc',
    appId: '1:151892709562:android:03c6f48538544c1ef0b283',
    messagingSenderId: '151892709562',
    projectId: 'farm-erp-2023',
    databaseURL: 'https://farm-erp-2023-default-rtdb.firebaseio.com',
    storageBucket: 'farm-erp-2023.appspot.com',
  );
}